# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/SoC/LCD_V3/LCD_V2/LCD_h.cache/wt [current_project]
set_property parent.project_path E:/SoC/LCD_V3/LCD_V2/LCD_h.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.4 [current_project]
set_property ip_output_repo e:/SoC/LCD_V3/LCD_V2/LCD_h.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_BRAM/AHB2BRAM.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_BUS/AHBDCD.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_GPIO/AHBGPIO.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_LCD/AHBLCD.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_BUS/AHBMUX.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_TIMER/AHBTIMER.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/CortexM0-DS/CORTEXM0INTEGRATION.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/CortexM0-DS/cortexm0ds_logic.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHB_TIMER/prescaler.v
  E:/SoC/LCD_V3/LCD_V2/lab_files/FPGA/AHBLITE_SYS.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/SoC/LCD_V3/LCD_V2/lab_files/lcd.xdc
set_property used_in_implementation false [get_files E:/SoC/LCD_V3/LCD_V2/lab_files/lcd.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AHBLITE_SYS -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AHBLITE_SYS.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AHBLITE_SYS_utilization_synth.rpt -pb AHBLITE_SYS_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
